//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %LOCALAPPDATA%\Committee of Zero\SG0\config.json.
        /// </summary>
        public static string ConfigJsonPath {
            get {
                return ResourceManager.GetString("ConfigJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to read configuration. Regenerating..
        /// </summary>
        public static string ConfigurationReadError {
            get {
                return ResourceManager.GetString("ConfigurationReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to save configuration..
        /// </summary>
        public static string ConfigurationSaveError {
            get {
                return ResourceManager.GetString("ConfigurationSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your configuration file is for an incompatible version of LanguageBarrier..
        /// </summary>
        public static string ConfigurationSchemaMismatchError {
            get {
                return ResourceManager.GetString("ConfigurationSchemaMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit text for consistency with the original STEINS;GATE VN translation (Name order, terminology, etc.).
        /// </summary>
        public static string ConsistencyLabel {
            get {
                return ResourceManager.GetString("ConsistencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes and Exit.
        /// </summary>
        public static string DiscardExitLabel {
            get {
                return ResourceManager.GetString("DiscardExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes (reload config).
        /// </summary>
        public static string DiscardLabel {
            get {
                return ResourceManager.GetString("DiscardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Uri similar to http://sonome.dareno.me/projects/sghd.html#jpvideo.
        /// </summary>
        public static System.Uri EnableJpVideoSubsUri {
            get {
                object obj = ResourceManager.GetObject("EnableJpVideoSubsUri", resourceCulture);
                return ((System.Uri)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video options.
        /// </summary>
        public static string FmvHeader {
            get {
                return ResourceManager.GetString("FmvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        public static string GeneralHeader {
            get {
                return ResourceManager.GetString("GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For videos with music, play high-quality BGM instead of the included low-quality audio tracks..
        /// </summary>
        public static string HqFmvAudioLabel {
            get {
                return ResourceManager.GetString("HqFmvAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw improved outlines for dialogue (disable if you prefer the original)..
        /// </summary>
        public static string ImproveDialogueOutlinesLabel {
            get {
                return ResourceManager.GetString("ImproveDialogueOutlinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality.
        /// </summary>
        public static string KaraokeSubsHighQualityOption {
            get {
                return ResourceManager.GetString("KaraokeSubsHighQualityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karaoke subtitles:.
        /// </summary>
        public static string KaraokeSubsLabel {
            get {
                return ResourceManager.GetString("KaraokeSubsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple effects.
        /// </summary>
        public static string KaraokeSubsLowQualityOption {
            get {
                return ResourceManager.GetString("KaraokeSubsLowQualityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string KaraokeSubsOffOption {
            get {
                return ResourceManager.GetString("KaraokeSubsOffOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use solid black (instead of white with shadow) text for names in RINE..
        /// </summary>
        public static string RineBlackNamesLabel {
            get {
                return ResourceManager.GetString("RineBlackNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LauncherEng.exe.
        /// </summary>
        public static string RunGameUri {
            get {
                return ResourceManager.GetString("RunGameUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/Exit/Run Launcher.
        /// </summary>
        public static string SaveExitLabel {
            get {
                return ResourceManager.GetString("SaveExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageBarrier for Zero - internal testing v2.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageBarrier Config.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
