//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %LOCALAPPDATA%\VNX+\SGHDbr\config.json.
        /// </summary>
        public static string ConfigJsonPath {
            get {
                return ResourceManager.GetString("ConfigJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar ler configurações. Criando novas....
        /// </summary>
        public static string ConfigurationReadError {
            get {
                return ResourceManager.GetString("ConfigurationReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar salvar configurações..
        /// </summary>
        public static string ConfigurationSaveError {
            get {
                return ResourceManager.GetString("ConfigurationSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu arquivo de configuração foi feito em uma versão incompatível do LanguageBarrier..
        /// </summary>
        public static string ConfigurationSchemaMismatchError {
            get {
                return ResourceManager.GetString("ConfigurationSchemaMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descartar alterações e fechar.
        /// </summary>
        public static string DiscardExitLabel {
            get {
                return ResourceManager.GetString("DiscardExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descartar alterações (recarregar).
        /// </summary>
        public static string DiscardLabel {
            get {
                return ResourceManager.GetString("DiscardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Uri similar to http://sonome.dareno.me/projects/sghd.html#jpvideo.
        /// </summary>
        public static System.Uri EnableJpVideoSubsUri {
            get {
                object obj = ResourceManager.GetObject("EnableJpVideoSubsUri", resourceCulture);
                return ((System.Uri)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar legendas de karaokê..
        /// </summary>
        public static string EnableKaraokeSubsLabel {
            get {
                return ResourceManager.GetString("EnableKaraokeSubsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar efeitos simples (para PCs lentos)..
        /// </summary>
        public static string EnableLqKaraokeSubsLabel {
            get {
                return ResourceManager.GetString("EnableLqKaraokeSubsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solucionar possível problema onde o jogo não responde quando fechado em tela cheia..
        /// </summary>
        public static string ExitBlackScreenFixLabel {
            get {
                return ResourceManager.GetString("ExitBlackScreenFixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções de vídeo.
        /// </summary>
        public static string FmvHeader {
            get {
                return ResourceManager.GetString("FmvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma fonte:.
        /// </summary>
        public static string FontLabel {
            get {
                return ResourceManager.GetString("FontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noto Sans.
        /// </summary>
        public static string FontNotoSansOption {
            get {
                return ResourceManager.GetString("FontNotoSansOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        public static string FontPlaceholderOption {
            get {
                return ResourceManager.GetString("FontPlaceholderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubuntu.
        /// </summary>
        public static string FontUbuntuOption {
            get {
                return ResourceManager.GetString("FontUbuntuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções gerais.
        /// </summary>
        public static string GeneralHeader {
            get {
                return ResourceManager.GetString("GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprimorar tipografia utilizada em textos e habilitar quebra de linha nas mensagens de celular..
        /// </summary>
        public static string ImproveTextDisplayLabel {
            get {
                return ResourceManager.GetString("ImproveTextDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam://run/412830.
        /// </summary>
        public static string RunGameUri {
            get {
                return ResourceManager.GetString("RunGameUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar/Fechar/Abrir Launcher.
        /// </summary>
        public static string SaveExitLabel {
            get {
                return ResourceManager.GetString("SaveExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar alterações.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forçar filtragem bilinear. Essa opção melhora significantemente a qualidade visual em cenas com zoom e resoluções abaixo de 1080p..
        /// </summary>
        public static string TextureFilteringLabel {
            get {
                return ResourceManager.GetString("TextureFilteringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durante a reprodução de vídeos com música, substituir faixas de áudio de baixa qualidade por versões de melhor qualidade..
        /// </summary>
        public static string UseHqAudioLabel {
            get {
                return ResourceManager.GetString("UseHqAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageBarrier para STEINS;GATE PT-BR - Versão 1.03.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações do LanguageBarrier.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
